name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees:
  - ngtrthinh169TPC
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviours
      description: What did you expect to happen?
      placeholder: What should it behave?
      value: "It should have worked!"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviours
      description: What actually happened?
      placeholder: Tell us what you see!
      value: "It bugged"
    validations:
      required: true
  - type: dropdown
    id: screensize
    attributes:
      label: What device are you seeing the problem on?
      multiple: true
      options:
        - Mobile
        - Desktop
        - Laptop
        - Tablet
        - Something else
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      # description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      description: Well we don't have Code of Conduct yet lol.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
