name: Feature Idea
description: Have an idea to improve this project? Let me know~
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - ngtrthinh169TPC
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help me improve
  - type: textarea
    id: your-big-idea
    attributes:
      label: Your idea
      description: What is your suggestion to improve this project?
      placeholder: Let's improve this!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context of your idea
      description: Why do you think it should be included in this project? At which context did it meet the need of this feature?
      placeholder: "Oh, it will help"
    validations:
      required: true
  - type: textarea
    id: direction
    attributes:
      label: Do you have a suggestion of how to do this?
      description: Show me how we do it! *optional*
  - type: checkboxes
    id: terms
    attributes:
      label: Disclaimer
      description: By submitting this issue, you also acknowledge that I am not forced to make this feature but taking this as an inspiration.
      options:
        - label: I acknowledge that my idea will be used for this project with my consent
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
